server:
  port: 1000
  error:
    include-message: always
    include-binding-errors: always

oauth:
  google:
    clientId: "557931936658-7ih5tuu8gepkncbuj7r8dabts6le2609.apps.googleusercontent.com"
    clientSecret: "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"
    scope: "openid profile email"

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  config:
    import: optional:consul:/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
    gateway:
      routes:
        - id: gateway-oauth-route
          uri: lb://gateway
          predicates:
            - Path=/oauth/**
        - id: intern-task-2
          uri: lb://intern-task-2
          predicates:
            - Path=/api/v1/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /api/v1/${remaining}
  r2dbc:
    url: "r2dbc:h2:mem:///gwsdb"
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
